[tool.poetry]
name = "youchat-py"
version = "0.1.0"
description = ""
readme = "README.md"
packages = [{include = "youchat"}]

[tool.poetry.dependencies]
python = "^3.7"
seleniumbase = "^4.18.1"

[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"